# Generated by Django 3.2.8 on 2021-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_head_portrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='picture',
        ),
        migrations.AddField(
            model_name='content',
            name='desc',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='content',
            table='article',
        ),
    ]
