# Generated by Django 3.2.8 on 2021-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211107_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default='/head_portrait/head_portrait.jpg', upload_to='head_portrait', verbose_name='头像'),
        ),
    ]
